[package]
name = "minifb"
version = "0.1.0"
authors = ["Daniel Collin <daniel@collin.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3.19"

[dependencies]
libc = "0.1.10"
user32-sys = "0.1.2"
winapi = "0.2.4"
kernel32-sys = "0.1.4"
gdi32-sys = "0.1.1"

[target.x86_64-apple-darwin.dependencies]
objc = "0.1.8"
cgl = "0.1"
cocoa = "0.1.4"
core-foundation = "0"
core-graphics = "0"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.2.4"
user32-sys = "0.1.2"
kernel32-sys = "0.1.4"
gdi32-sys = "0.1.1"

[target.i686-pc-windows-msvc.dependencies]
winapi = "0.2.4"
user32-sys = "0.1.2"
kernel32-sys = "0.1.4"
gdi32-sys = "0.1.1"



